// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:app/app/internal/core/job.dart';
import 'package:app/app/internal/core/pagination.dart';
import 'package:app/app/internal/data/database.dart';
import 'package:app/app/internal/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ImageJobRepository>>
abstract class ImageJobRepository implements RustOpaqueInterface {
  factory ImageJobRepository({required ArcConnection db}) =>
      RustLib.instance.api.crateCoreImagesImageJobRepositoryNew(db: db);
  Future<PlatformInt64> createJob({required String prompt});

  Future<ImageJob?> findById({required PlatformInt64 id});

  Future<List<ImageJob>> findByStatus({
    required JobStatus status,
    required Pagination pagination,
  });

  Future<void> init();

  Future<List<ImageJob>> load({required Pagination pagination});

  Future<void> removeJob({required PlatformInt64 id});

  Future<void> setImagePath({
    required PlatformInt64 id,
    required String imagePath,
  });

  Future<void> updateStatus({
    required PlatformInt64 id,
    required JobStatus status,
  });
}

class ImageJob {
  const ImageJob({
    required this.id,
    required this.prompt,
    required this.status,
    required this.imagePath,
  });
  final PlatformInt64 id;
  final String prompt;
  final JobStatus status;
  final String imagePath;

  @override
  int get hashCode =>
      id.hashCode ^ prompt.hashCode ^ status.hashCode ^ imagePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageJob &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          prompt == other.prompt &&
          status == other.status &&
          imagePath == other.imagePath;
}
