// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:app/app/internal/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < Connection >>>
abstract class ArcConnection implements RustOpaqueInterface {}

class Database {
  const Database();

  static Future<ArcConnection> connection({required String appDirectory}) =>
      RustLib.instance.api.crateDataDatabaseDatabaseConnection(
        appDirectory: appDirectory,
      );

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Database && runtimeType == other.runtimeType;
}
