name: app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_rust_bridge: 2.9.0
  go_router: ^15.1.1
  hooks_riverpod: ^2.6.1
  lucide_icons_flutter: ^3.0.0
  path_provider: ^2.1.5
  rust_lib_app:
    path: rust_builder

dev_dependencies:
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  riverpod_lint: ^2.6.5
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
